name: Create Flatpak

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
        username:
            description: 'xfel username'
            required: true
        password:
            description: 'xfel password'
            required: true

jobs:
  flatpak:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Flatpak
      run: |
        sudo apt install flatpak flatpak-builder

    - name: Setup Flatpak
      run: |
        flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install flathub org.kde.Platform//5.15 org.kde.Sdk//5.15 -y

    - name: Build Flatpak
      run: |
        sed -i 's/{USER}/${{ github.event.inputs.username }}/g' eu.xfel.karabo.gui.yml
        sed -i 's/{PASS}/${{ github.event.inputs.password }}/g' eu.xfel.karabo.gui.yml
        flatpak-builder --repo=repo --force-clean build-dir eu.xfel.karabo.gui.yml

    - name: Build Bundle
      run: |
        flatpak build-bundle repo karabo.gui.flatpak eu.xfel.karabo.gui

    - name: Upload Flatpak
      uses: actions/upload-artifact@v2
      with:
        name: karabo.gui.flatpak
        path: ./karabo.gui.flatpak
